
services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
     - mongo_data:/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      DB_NAME: myKeyValueDB
      COLLECTION_NAME: kv_store
      MONGODB_URI: mongodb://mongo:27017/
    depends_on:
      - mongo

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always

  gateway:
    
    build: ./gateway
    ports:
      - 3000:3000
    restart: always
    depends_on:
      read:
        condition: service_started

  read:
    build: ./read_service
    restart: always
    environment:
      READ_SERVICE_PORT: 2500
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      mongo:
        condition: service_started

  write:
    build: ./write_que
    restart: always
    environment:
      QUEUE_Service_port: 2000
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started

  worker:
    build: ./write_dbq
    restart: always
    environment:
      WriteDb: 4000
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started

volumes:
  redis_data:
  mongo_data:

